shm_file_path = "/tmp/lithos_md_bus"

log_level = "debug"

capacity = 65536

[[connections]]
url = "wss://stream.binance.com:9443/ws/btcusdt@bookTicker"
symbol_id = 1

[[connections]]
url = "wss://stream.binance.com:9443/ws/ethusdt@bookTicker"
symbol_id = 2