[package]
name = "onyx"
version = "0.1.0"
edition = "2024"

[dependencies]
onyx-engine = {path = "../../crates/onyx/onyx-engine"}
onyx-config = {path = "../../crates/onyx/onyx-config"}
tracing-subscriber = { workspace = true }
tracing = { workspace = true }