[package]
name = "obsidian-util"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2"

[dev-dependencies]
criterion = "0.5"
obsidian-core = { path = "../obsidian-core" }
sonic-rs = "0.5.6"

[[bench]]
name = "binance_parse"
harness = false
