[package]
name = "obsidian"
version = "0.1.0"
edition = "2024"

[dependencies]
lithos-events = {path = "../../crates/lithos/lithos-events"}
lithos-icc = {path = "../../crates/lithos/lithos-icc"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tungstenite = {version = "0.28.0" , features = ["native-tls" , "rustls"]}
